Vinhoteca/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Vinhos
from .models import Inventario
from .models import Vinicola
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
from . import db
import json
import csv
from sqlalchemy import or_

class Views:
    views = Blueprint('views', __name__)

    @views.route('/', methods=['GET', 'POST'])
    @login_required
    def home():
        inventarios_usuario = Inventario.query.filter_by(user_id=current_user.id).all()

        vinhos_ids_distintos = set(inventario.vinho_id for inventario in inventarios_usuario)
        vinhos_inventario = Vinhos.query.filter(Vinhos.id.in_(vinhos_ids_distintos)).all()

        if request.method == 'POST': 
            if 'buscar' in request.form:
                    nome = request.form.get('buscar')
                    vinhos = Vinhos.query.filter(Vinhos.nome.ilike(f'%{nome}%'))
                    return render_template("home.html", vinhos=vinhos, inventario=inventarios_usuario, user=current_user)

        return render_template("home.html", vinhos=vinhos_inventario, inventario=inventarios_usuario, user=current_user)

    def validate_wine(nome, safra, uva, tempodeguarda, harmonizacao):
        if len(nome) < 1: # create a validate input function
            flash('Nome inválido!', category='error')
            return 0
        
        elif len(safra) < 4:
            flash('Safra inválida!', category='error')
            return 0
        
        elif len(uva) < 1:
            flash('Uva inválida!', category='error')
            return 0
        
        elif len(tempodeguarda) < 1:
            flash('Tempo de guarda inválido!', category='error')
            return 0
        
        elif len(harmonizacao) < 1:
            flash('Harmonização inválida!', category='error')
            return 0
        
        return 1
    
    """"
    def register_wine(nome, safra, uva, tempodeguarda, harmonizacao):
        novo_vinho = Vinhos(nome=nome, safra=safra, uva=uva, tempodeguarda = tempodeguarda, harmonizacao=harmonizacao)  #providing the schema for the note 
        db.session.add(novo_vinho) #adding the note to the database 
        db.session.commit()
        flash('Vinho Adicionado!', category='success') """

    def register_wine(nome, safra, uva, tempodeguarda, harmonizacao, vinicola_nome, vinicola_regiao):
        vinicola = Vinicola.query.filter_by(nome=vinicola_nome).first()
        if vinicola:
            vinicola_id = vinicola.id
        else:
            nova_vinicola = Vinicola(nome=vinicola_nome, regiao=vinicola_regiao)
            db.session.add(nova_vinicola)
            db.session.commit()
            vinicola_id = nova_vinicola.id
    
        novo_vinho = Vinhos(nome=nome, safra=safra, uva=uva, tempodeguarda=tempodeguarda, harmonizacao=harmonizacao, vinicola_id=vinicola_id)
        db.session.add(novo_vinho)
        db.session.commit()
        flash('Vinho Adicionado!', category='success')


    @views.route('/cadastro', methods=['GET', 'POST'])
    @login_required
    def register():
        if request.method == 'POST': 
            
            if 'add' in request.form:
                return redirect(url_for('views.home'))
            
            if 'register' in request.form:
                nome = request.form.get('nome')#Gets the note from the HTML 
                safra = request.form.get('safra')
                uva = request.form.get('uva')
                tempodeguarda = request.form.get('tempodeguarda')
                harmonizacao = request.form.get('harmonizacao')   
                vinicola_nome = request.form.get('vinicola.nome')     
                vinicola_regiao = request.form.get('vinicola.regiao')                
                
                if Views.validate_wine(nome,safra,uva,tempodeguarda,harmonizacao):
                    Views.register_wine(nome,safra,uva,tempodeguarda,harmonizacao,vinicola_nome,vinicola_regiao)

            if 'procura' in request.form:
                nome = request.form.get('procura_vinho')
                vinhos = Vinhos.query.filter(Vinhos.nome.ilike(f'%{nome}%'))
                return render_template("wine_register.html", vinhos=vinhos, user=current_user)

        vinhos = Vinhos.query.all()
        return render_template("wine_register.html", vinhos=vinhos, user=current_user)

    @views.route('/harmonizacao', methods=['GET', 'POST'])
    @login_required
    def pairing():
        if request.method == 'POST': 
            if 'harmonize' in request.form:
                harmonizacao = request.form.get('harmonizacao')
                vinhos = Vinhos.query.filter(Vinhos.harmonizacao.ilike(f'%{harmonizacao}%'))
                return render_template("wine_pairing.html", vinhos=vinhos, user=current_user)
    
        return render_template("wine_pairing.html", vinhos=None, user=current_user)


    @views.route('/delete-vinho', methods=['POST'])
    def delete_vinho():  
        vinho = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
        vinhoId = vinho['vinhoId']
        vinho = Vinhos.query.get(vinhoId)
        if vinho:
            if vinho.user_id == current_user.id:
                db.session.delete(vinho)
                db.session.commit()

        return jsonify({})

    @views.route('/adicionar/<int:vinho_id>', methods=['GET', 'POST'])
    @login_required
    def add_wine(vinho_id):
        if request.method == 'POST':
            if 'addvinho' in request.form:
                print(vinho_id)
                localizacao = request.form.get('localizacao')
                quantidade = request.form.get('quantidade')
                print(current_user)

                novo_inventario = Inventario(localizacao=localizacao, quantidade=quantidade, user_id=current_user.id, vinho_id=vinho_id)  #providing the schema for the note 
                db.session.add(novo_inventario) #adding the note to the database 
                db.session.commit()

                flash('Vinho Adicionado!', category='success')
                return redirect(url_for('views.home'))

        return render_template("add_wine.html", user=current_user)

    @views.route('/remover_vinho/<int:vinho_id>/<int:inventario_id>', methods=['POST'])
    @login_required
    def remover_vinho(vinho_id, inventario_id):
        inventario = Inventario.query.filter_by(user_id=current_user.id, vinho_id=vinho_id, id=inventario_id).first()

        if inventario:
            db.session.delete(inventario)
            db.session.commit()
            flash('Vinho removido do inventário com sucesso.', 'success')
        else:
            flash('Vinho não encontrado no inventário.', 'error')

        return redirect(url_for('views.home'))

    
    @views.route('/editar_vinho/<int:vinho_id>/<int:inventario_id>', methods=['POST'])
    @login_required
    def editar_vinho(vinho_id, inventario_id):
        inventario = Inventario.query.filter_by(id=inventario_id, vinho_id=vinho_id, user_id=current_user.id).first()

        if inventario:
            quantidade = request.form.get('quantidade')
            localizacao = request.form.get('localizacao')

            if quantidade:
                inventario.quantidade = quantidade

            if localizacao:
                inventario.localizacao = localizacao

            db.session.commit()
            flash('Dados do vinho editados com sucesso.', 'success')
        else:
            flash('Vinho não encontrado no inventário.', 'error')

        return redirect(url_for('views.home'))

Vinhoteca/website/templates/add_wine.html
{% extends "base.html" %}
{% block modal %}
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Adicionar Vinho a Minha Adega</h5>
        </div>
        <div class="modal-body">
            <form method="POST">
                <div class="form-group">
                    <label for="quantidade">Quantidade:</label>
                    <input type="number" class="form-control" name="quantidade" id="quantidade"> </input>
                </div>
                <div class="form-group">
                    <label for="localizacao">Localização:</label>
                    <input type="text" class="form-control" name="localizacao" id="localizacao"> </input>
                </div>
        </div>
        <div class="modal-footer">
                <button type="submit" name="addvinho" class="btn btn-primary">Adicionar</button>
                <a href="{{url_for('views.register')}}" class="btn btn-dark">Fechar</a>
            </form>

            
        </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function(){
        $("#exampleModal").modal("show")
    })
</script>
{% endblock %}

Vinhoteca/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #54252f; font-size: large; ">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="{{url_for('static', filename='logo2.png')}}" width="70" height="70" />
      </a>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/" style="color: #fdebbb;">Minha Adega</a>
          <a class="nav-item nav-link" id="harmonizacao" href="/harmonizacao" style="color: #fdebbb;">Harmonização</a>
          <a class="nav-item nav-link" id="register" href="/cadastro" style="color: #fdebbb;">Cadastrar Vinho</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login"style="color: #fdebbb;">Entrar</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up"style="color: #fdebbb;">Cadastrar-se</a>
          {% endif %}
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout"style="color: #fdebbb;">Sair</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    
    {% block modal %} 
    {% endblock %}

{% block javascript %}
    <script type="text/javascript">
      function deleteVinho(vinhoId) {
  fetch("/delete-vinho", {
    method: "POST",
    body: JSON.stringify({ vinhoId: vinhoId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

Vinhoteca/website/templates/home.html
{% extends "base.html" %} {% block title %}Vinhoteca{% endblock %} {% block content
  %}
<h1 align="center" style="padding-top: 30px; padding-bottom: 30px;">Minha Adega</h1>

<form method="POST">
  <div class="input-group mb-3 d-flex justify-content-center" style="margin-bottom: 50px; margin-top: 50px;">
      <input type="text" class="form-control" style="max-width: 700px;" placeholder="Buscar na Minha Adega..." aria-label="Recipient's username" aria-describedby="basic-addon2" name="buscar" id="buscar">
      <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="submit" name="buscar">Procurar</button>
      </div>
  </div>
</form>

<div class="row mt-4">
  {% for vinho in vinhos %}
    {% for inventario in inventario %}
      {% if vinho.id == inventario.vinho_id %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h5 class="card-title">{{ vinho.nome }}</h5>
              <p class="card-text">Safra: {{ vinho.safra }}</p>
              <p class="card-text">Uva: {{ vinho.uva }}</p>
              <p class="card-text">Tempo de Guarda: {{ vinho.tempodeguarda }}</p>
              <p class="card-text">Harmonização: {{ vinho.harmonizacao }}</p>
              <p class="card-text">Quantidade: {{ inventario.quantidade }}</p>
              <p class="card-text">Localização: {{ inventario.localizacao }}</p>

              <!-- Dentro do loop que itera sobre os inventários -->
              <form id="edit-form-{{ vinho.id }}-{{ inventario.id }}" class="edit-form" style="display: none;" method="POST" action="{{ url_for('views.editar_vinho', vinho_id=vinho.id, inventario_id=inventario.id) }}">
                <!-- Campo de edição da quantidade -->
                <label for="editquantidade">Editar Quantidade:</label>
                <input type="number" name="quantidade">
                <!-- Campo de edição da localização -->
                <label for="editlocalizacao">Editar Localização:</label>
                <input type="text" name="localizacao">
                <button type="submit" class="btn btn-primary">Salvar</button> 
              </form>

              <button class="btn btn-info edit-button" onclick="toggleEditForm('edit-form-{{ vinho.id }}-{{ inventario.id }}')">Editar</button>

              <script>
                // Função para exibir/ocultar o formulário de edição
                function toggleEditForm(formId) {
                  var form = document.getElementById(formId);
                  if (form.style.display === "none") {
                    form.style.display = "block";
                  } else {
                    form.style.display = "none";
                  }
                }
              </script>

              <form method="POST" action="{{ url_for('views.remover_vinho', vinho_id=vinho.id, inventario_id=inventario.id) }}">
                <button type="submit" class="btn btn-danger mt-2">Remover</button>
              </form>

            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  {% endfor %}
</div>




<!--
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{{url_for('static', filename='wine.jpeg')}}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{{url_for('static', filename='wine.jpeg')}}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{{url_for('static', filename='wine.jpeg')}}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
-->
  {% endblock %}

Vinhoteca/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email"
    />
  </div>
  <div class="form-group">
    <label for="password">Senha</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Senha"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Vinhoteca/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Cadastra-se{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Cadastrar-se</h3>
  <div class="form-group">
    <label for="email">Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">Primeiro Nome</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Senha</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Senha (Confirmação)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>
{% endblock %}

Vinhoteca/website/templates/wine_pairing.html
{% extends "base.html" %} {% block title %}Harmonização{% endblock %} {% block content
    %}
<h1 align="center" style="padding-top: 30px; padding-bottom: 30px;">Harmonização</h1>

<form method="POST">
  <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="O que quero comer hoje?" aria-label="Recipient's username" aria-describedby="basic-addon2" name="harmonizacao" id="harmonizacao">
      <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="submit" name="harmonize">Harmonize!</button>
      </div>
  </div>
</form>


{% if vinhos is not none %}
  <div class="row">
    {% for vinho in vinhos %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h5 class="card-title">{{ vinho.nome }}</h5>
            <p class="card-text">Safra: {{ vinho.safra }}</p>
            <p class="card-text">Uva: {{ vinho.uva }}</p>
            <p class="card-text">Tempo de Guarda: {{ vinho.tempodeguarda }}</p>
            <p class="card-text">Harmonização: {{ vinho.harmonizacao }}</p>
            <p class="card-text">Vinícola: {{ vinho.vinicola.nome }}</p>
            <p class="card-text">Região: {{ vinho.vinicola.regiao }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}

{% endblock %}

Vinhoteca/website/templates/wine_register.html
{% extends "base.html" %} {% block title %}Cadastro{% endblock %} {% block content
    %}
   
    <div class="card mx-auto" style="max-width: 600px; margin-bottom: 20px; margin-top: 20px;">
        <h5 class="card-header text-center">Cadastrar Novo Vinho</h5>
        <div class="card-body">
          <form method="POST">
            <div class="form-group">
              <label for="nome">Nome:</label>
              <input type="text" class="form-control" name="nome" id="nome"> </input>
            </div>
            <div class="form-group">
              <label for="safra">Safra:</label>
              <input type="number" class="form-control" name="safra" id="safra"> </input>
            </div>
            <div class="form-group">
              <label for="uva">Uva:</label>
              <input type="text" class="form-control" name="uva" id="uva"> </input>
            </div>
            <div class="form-group">
              <label for="tempodeguarda">Tempo de Guarda:</label>
              <input type="number" class="form-control" name="tempodeguarda" id="tempodeguarda"> </input>
            </div>
            <div class="form-group">
              <label for="harmonizacao">Harmonização:</label>
              <input type="text" class="form-control" name="harmonizacao" id="harmonizacao"> </input>
            </div>      
            <div class="form-group">
              <label for="vinicola.nome">Vinícola:</label>
              <input type="text" class="form-control" name="vinicola.nome" id="vinicola.nome"> </input>
            </div>       
            <div class="form-group">
              <label for="vinicola.regiao">Região:</label>
              <input type="text" class="form-control" name="vinicola.regiao" id="vinicola.regiao"> </input>
            </div>  
            <div class="text-center">
                <button type="submit" name="register" class="btn btn-primary">Cadastrar</button>
            </div>
          </form>
        </div>
      </div>
      
      <form method="POST">
        <div class="input-group mb-3 d-flex justify-content-center" style="margin-bottom: 50px; margin-top: 50px;">
            <input type="text" class="form-control" style="max-width: 700px;" placeholder="Que vinho deseja?" aria-label="Recipient's username" aria-describedby="basic-addon2" name="procura_vinho" id="procura_vinho">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit" name="procura">Procurar</button>
            </div>
        </div>
      </form>
  
    <div class="row mt-4">
        {% for vinho in vinhos %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <div class="card-body">
                <h5 class="card-title">{{ vinho.nome }}</h5>
                <p class="card-text">Safra: {{ vinho.safra }}</p>
                <p class="card-text">Uva: {{ vinho.uva }}</p>
                <p class="card-text">Tempo de Guarda: {{ vinho.tempodeguarda }}</p>
                <p class="card-text">Harmonização: {{ vinho.harmonizacao }}</p>
                <p class="card-text">Vinícola: {{ vinho.vinicola.nome }}</p>
                <p class="card-text">Região: {{ vinho.vinicola.regiao }}</p>
                <a href="{{url_for('views.add_wine', vinho_id=vinho.id)}}" class="btn btn-dark">Adicionar a Minha Adega</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      
    
    {% endblock %}
    